version: '2'
services:
    smscenter-app:
        image: smscenter
            - smscenter-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/smscenter
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smscenter-mariadb:
        extends:
            file: mariadb.yml
            service: smscenter-mariadb
